### ISSUE TITLE
ROTATE_DISPLAY not working

### ISSUE THREAD

**Issue by pallsopp** [balenablocks/browser#52]
Hey guys!

I have a really simple setup:

Fin CM3 4GB
Official RPi 7" display

docker-compose.yml

```
version: '2'

services:
  browser:
    image: balenablocks/browser:raspberrypi4-64
    privileged: true
    network_mode: host
    volumes:
      - 'settings:/data'
    restart: unless-stopped
    environment:
      - KIOSK=1
      - PERSISTENT=1
      - ROTATE_DISPLAY=inverted
      - LAUNCH_URL=http://google.com

volumes:
  settings:
```

However, the display is always in the normal mode.
I've tried playing around with different settings from balenaDash and balenaBrowser but no luck so far.

If I have to switch to the cloud to configure it, that's fine, but I'm in local mode right now.

Thanks for any help.
Paul
