### ISSUE TITLE
Browser block does not run on rpi4

### ISSUE THREAD

**Issue by abhatikar** [balenablocks/browser#77]
Just a basic push and it does not come up

> [Logs]    [9/4/2021, 8:38:29 AM] Service exited 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:39:21 AM] Restarting service 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:39:22 AM] [browser] Running balena base image entrypoint...
[Logs]    [9/4/2021, 8:39:22 AM] [browser] setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
[Logs]    [9/4/2021, 8:39:27 AM] [browser] Using default chromium flags
[Logs]    [9/4/2021, 8:39:27 AM] [browser] Enabling GPU acceleration
[Logs]    [9/4/2021, 8:39:27 AM] [browser] Custom window size set to 800,600
[Logs]    [9/4/2021, 8:39:27 AM] [browser] Using default window position
[Logs]    [9/4/2021, 8:39:27 AM] [browser] Enabling kiosk mode
[Logs]    [9/4/2021, 8:39:27 AM] [browser] Enabling cursor
[Logs]    [9/4/2021, 8:39:31 AM] Service exited 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:40:32 AM] Restarting service 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'
[Logs]    [9/4/2021, 8:40:32 AM] [browser] Running balena base image entrypoint...
[Logs]    [9/4/2021, 8:40:33 AM] [browser] setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
[Logs]    [9/4/2021, 8:40:34 AM] [browser] Using default chromium flags
[Logs]    [9/4/2021, 8:40:34 AM] [browser] Enabling GPU acceleration
[Logs]    [9/4/2021, 8:40:34 AM] [browser] Custom window size set to 800,600
[Logs]    [9/4/2021, 8:40:34 AM] [browser] Using default window position
[Logs]    [9/4/2021, 8:40:34 AM] [browser] Enabling kiosk mode
[Logs]    [9/4/2021, 8:40:34 AM] [browser] Enabling cursor
[Logs]    [9/4/2021, 8:40:38 AM] Service exited 'browser sha256:fa7ca3bc2ac4314d5f68595bb8cb219c1b9259cffa39ae6f4617f1024543104c'

**Comment by pymoreau** [comment]
I have the same problem but it works if you downgrade the balenaOS to the v2.80.5+rev1

**Comment by danthegoodman1** [comment]
@abhatikar Would you be able to share your docker compose file?

**Comment by abhatikar** [comment]
As mentioned its the default docker-compose from the repo. However, reverting to previous release of balena os, the browser block works.

**Comment by drewcovi** [comment]
@rahul-thakoor running `balenaOS 2.83.10+rev1` still seems to have this issue restarting... any specific image I should target in my docker-compose?

**Comment by drewcovi** [comment]
```yml
  kiosk:
    image: balenablocks/browser:raspberrypi4-64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
```

```bash
 kiosk  Running balena base image entrypoint...
 kiosk  setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
 kiosk  Using default chromium flags
 kiosk  Disabling GPU acceleration
 kiosk  Adding user settings directory
 kiosk  Using fullscreen: 1824,984
 kiosk  Enabling kiosk mode
 kiosk  Disabling cursor
```
